// Generated by LinoJava. Do not edit.
export const metadata = {"backend":"javascript-basic-blocks","memoryUnits":5,"blocks":6};
const symbolTable = {"player_x":{"name":"player_x","kind":"memory","address":0},"player_y":{"name":"player_y","kind":"memory","address":1},"input_x":{"name":"input_x","kind":"memory","address":2},"input_y":{"name":"input_y","kind":"memory","address":3},"frame":{"name":"frame","kind":"memory","address":4}};
const initialMemory = [154,92,0,0,0];
export function createProgram(host = {}) {
  const mem = new Int32Array(initialMemory);
  let A = 0, B = 0, C = 0, D = 0, E = 0;
  let pc = 0;
  let halted = false;
  const callStack = [];
  function step(maxBlocks = 100000) {
    if (halted) return { status: "halted", blocks: 0 };
    let executed = 0;
    run: while (executed < maxBlocks) {
      executed += 1;
      switch (pc) {
        case 0: {
        A = (mem[(0) >>> 0]) | 0;
        A = (A + (mem[(2) >>> 0])) | 0;
        mem[(0) >>> 0] = (A) | 0;
        if (((A) | 0) >= ((314) | 0)) { pc = 1; continue run; }
        if (((A) | 0) >= ((2) | 0)) { pc = 2; continue run; }
        A = (2) | 0;
        mem[(0) >>> 0] = (A) | 0;
        pc = 2; continue run;
        }
        case 1: {
        A = (313) | 0;
        mem[(0) >>> 0] = (A) | 0;
        pc = 2; continue run;
        }
        case 2: {
        A = (mem[(1) >>> 0]) | 0;
        A = (A + (mem[(3) >>> 0])) | 0;
        mem[(1) >>> 0] = (A) | 0;
        if (((A) | 0) >= ((194) | 0)) { pc = 3; continue run; }
        if (((A) | 0) >= ((6) | 0)) { pc = 4; continue run; }
        A = (6) | 0;
        mem[(1) >>> 0] = (A) | 0;
        pc = 4; continue run;
        }
        case 3: {
        A = (193) | 0;
        mem[(1) >>> 0] = (A) | 0;
        pc = 4; continue run;
        }
        case 4: {
        mem[(4) >>> 0] = (mem[(4) >>> 0] + (1)) | 0;
        pc = 5;
        if (host.isocall?.(program) === true) return { status: "yield", blocks: executed };
        continue run;
        }
        case 5: {
        pc = 0; continue run;
        }
        default: halted = true; return { status: "halted", blocks: executed };
      }
    }
    return { status: "budget", blocks: executed };
  }
  const program = {
    memory: mem,
    symbols: symbolTable,
    step,
    get(name) { const symbol = symbolTable[String(name).toLowerCase()]; if (!symbol) throw new Error(`Unknown Lino symbol: ${name}`); return symbol.kind === "constant" ? symbol.value : mem[symbol.address]; },
    set(name, value) { const symbol = symbolTable[String(name).toLowerCase()]; if (!symbol || symbol.kind !== "memory") throw new Error(`Not a writable Lino symbol: ${name}`); mem[symbol.address] = value | 0; },
    snapshot() { return { version: 1, memory: Array.from(mem), registers: { A, B, C, D, E }, pc, halted, callStack: Array.from(callStack) }; },
    restore(saved) {
      if (!saved || saved.version !== 1 || !Array.isArray(saved.memory) || saved.memory.length !== mem.length) throw new Error("Incompatible LinoJava snapshot");
      mem.set(saved.memory.map((value) => value | 0));
      const registers = saved.registers ?? {};
      A = registers.A | 0; B = registers.B | 0; C = registers.C | 0; D = registers.D | 0; E = registers.E | 0;
      pc = saved.pc | 0; halted = Boolean(saved.halted);
      callStack.length = 0;
      if (Array.isArray(saved.callStack)) for (const value of saved.callStack) callStack.push(value | 0);
    },
    get registers() { return { A, B, C, D, E }; },
    get halted() { return halted; }
  };
  return program;
}
